### ISSUE TITLE
Getting Involved

### ISSUE THREAD

**Issue by jcooper67** [connorivy/beamOS-cs#42]
Hey Connor, 

I notice you labeled this project as open source and I was interested in getting involved. What's the best way to do that?

For some context : 

I'm a structural engineer by trade who's pursuing their masters in computer science ( I hold a bachelor and masters in Structural Engineering as well). I initially started programming because I was interested in developing my own analysis software. 

I'm mainly proficient in Java and Python but have some C# knowledge and can continue learning if you do need help with the project.

Thanks!

**Comment by connorivy** [comment]
Hey @jcooper67,

That is awesome to hear. Sounds like we have very similar backgrounds. 

Yeah, this repo is, at the moment, pretty much all c#. That decision was made because this is the language that many apis in the AEC industry are written in such as Revit, ETABS, and Tekla Structures. I even chose to use Blazor as the frontend framework because being able to push the c# execution to the client for heavy structural calcs will definitely save some money for me on the server hosting.

However, many structural engineers who have enough programming abilities to use something like this are probably more comfortable in Python. It would be interesting to see if a python SDK would be valuable to people.

This repo needs a ton of work in order for it to actually be useful. Unfortunately, I'm not really organized enough to let you know exactly what needs worked on at the moment, but I'm definitely open for suggestions if you see something that you want to work on. I'm happy to help you understand and navigate the existing code if you have any specific questions. I know it can be intimidating to make a PR to someone's repo, but you probably know more than I do about comp science so I wouldn't worry about that. I'm happy to help you understand and navigate the existing code if you have any specific questions. 

In terms of non-coding involvement, I'm always on the lookout for good examples of solved text-book problems that I can use to create tests. I've mostly been working on implementing the Direct Stiffness Method for solving indeterminate structures, and I haven't found a ton of great examples that deal with 3D frames.

**Comment by jcooper67** [comment]
Thanks for the reply! Totally agree on your implementation C# is definitely the way to go for something like this especially with how calculation heavy it will be. I'm still pretty fluent in C# for the most part so I should be able to piece everything together. I'll dive into it when I get some good free time. 

As for examples I actually have some matrix structural analysis books I can dig through. They're somewhat old but I'll see if I can find a PDF for you.

**Comment by jcooper67** [comment]
@connorivy I've got some examples from this book. I can send them to you or I can scan them and push them to the repo, whichever you prefer. Also, I'm having an issue building, is there a place I can ping you quickly to clarify some things? I'm sure I'm just misunderstanding the way Blazor apps run.
