### ISSUE TITLE
Push Access for Repository

### ISSUE THREAD

**Issue by jcooper67** [connorivy/beamOS-cs#47]
@connorivy 

I made some adjustments to the readme file and wanted to create a pull request for my branch but I don't have access to push to the repository.  Could you provide me that access? I can also just show you the changes I intended to make.

**Comment by connorivy** [comment]
Hey @jcooper67,

I very much appreciate the interest in making a PR. Pushing to a repo is a privilege that is typically reserved for code owners or team members. The recommended way to make a PR to an open-source project is to fork the repo and create a PR from the forked branch. [Here are some instructions](https://opensource.com/article/19/7/create-pull-request-github) on how to do that. This example uses the git cli which works fine, but I recommend using gitKraken because it has a very intuitive UI and is free to use on public repos
